---

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags: ["cjdns", "cjdns-install", "cjdns-configure", "cjdns-service"]

- name: Install cjdns dependencies package
  tags: ["cjdns"]
  apt:
    name: '{{item}}'
  with_items:
    - nodejs
    - git
    - build-essential
    - python2.7
    - ca-certificates

- name: Pull cjdns repo
  tags: ["cjdns"]
  git:
    repo: 'https://github.com/cjdelisle/cjdns/'
    dest: /home/cjdns
    version: cjdns-v20.3

- name: Build cjdns
  tags: ["cjdns"]
  shell: ./do >> build-with-ansible.log
  args:
    chdir: /home/cjdns/

- name: Symlink executable
  tags: ["cjdns"]
  file:
    src: /root/cjdns/cjdroute
    dest: /usr/bin/cjdroute
    owner: root
    group: root
    state: link
    mode: 0700

- name: Add cjdns service to systemd
  tags: ["cjdns", "cjdns-service"]
  copy:
    src=/home/cjdns/contrib/systemd/cjdns.service
    dest=/etc/systemd/system/cjdns.service
    remote_src=yes

- name: Add cjdns-resume service to systemd
  tags: ["cjdns", "cjdns-service"]
  copy:
    src=/root/cjdns/contrib/systemd/cjdns-resume.service
    dest=/etc/systemd/system/cjdns-resume.service
    remote_src=yes

- name: "Ensure existance of cjdns group"
  become: true
  group:
    name: "{{ cjdns_group }}"
    state: present
  tags: ["cjdns"]
  notify: ["restart cjdns"]

- name: "Ensure existance of cjdns user"
  become: true
  user:
    name: "{{ cjdns_user }}"
    group: "{{ cjdns_group }}"
    system: yes
  tags: ["cjdns"]
  notify: ["restart cjdns"]

- name: "Configure cjdns"
  become: true
  template:
    src: "cjdroute.conf.j2"
    dest: "/etc/cjdroute.conf"
    backup: "yes"
    owner: "{{ cjdns_user }}"
    group: "{{ cjdns_group }}"
    mode: "0640"
  tags: ["cjdns", "cjdns-configure"]
  notify: ["restart cjdns"]

# Let's try first with the upstream version
# - name: "Ensure modified systemd service file is installed"
#   become: true
#   template:
#     src: "cjdns.service.j2"
#     dest: "/etc/systemd/system/cjdns.service"
#     owner: "root"
#     group: "root"
#     mode: "0644"
#   register: "_cjdns_service_file"
#   tags: ["cjdns", "cjdns-service"]
#   notify: ["restart cjdns"]


- name: "Manage cjdns service"
  become: true
  service:
    name: "{{ cjdns_service_name }}"
    state: "{{ cjdns_service_state }}"
    enabled: "{{ cjdns_service_enabled }}"
    daemon_reload: "{{ _cjdns_service_file.changed | ternary('yes', 'no') }}"
  tags: ["cjdns", "cjdns-service"]
