---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance-0-debian
    image: docker.io/python:3.8-slim-buster
    pre_build_image: true
    groups:
      - vpc_1
  - name: instance-1-debian
    image: docker.io/python:3.8-slim-buster
    pre_build_image: true
    groups:
      - vpc_1

provisioner:
  name: ansible
  # This helps with create-debug
  log: true
verifier:
  name: ansible
